portals: &portals
  carve:
    org: ORNL DAAC
    title: CARVE
    params:
      project:
        - CARVE
    logos:
      - id: ornl-daac-logo
        image: /images/portals/ornl/ornl-daac-logo-mono.png
        link: https://carve.ornl.gov/
        title: ORNL DAAC CARVE Home
    scripts:
      - edsc-portal.ornl.min.js

  airmoss:
    org: ORNL DAAC
    title: AirMOSS
    params:
      project:
        - AirMOSS
    logos:
      - id: ornl-daac-logo
        image: /images/portals/ornl/ornl-daac-logo-mono.png
        link: https://airmoss.ornl.gov
        title: ORNL DAAC AirMOSS Home
    scripts:
      - edsc-portal.ornl.min.js

examples: &examples
  example:

  simple:
    params:
      echo_collection_id:
        - C90762182-LAADS

  complex:
    title: Complex
    params:
      echo_collection_id:
        - C90762182-LAADS
    logos:
      - image: http://placehold.it/75x50
        link: https://example.com/logo
    nav:
      - title: Example Link
        link: https://example.com/1
      - title: Another Example
        link: https://example.com/1
    scripts:
      - edsc-portal.example.min.js

defaults:
  <<: *examples
  <<: *portals

production:
  <<: *portals
