token_defaults: &token_defaults
  expires_in: 3600

token_user_username: <%= ENV['test_echo_token_username'] %>
token_user_password: <%= ENV['test_echo_token_password'] %>

urs_tokens:
  edsc:
    <<: *token_defaults
    access_token: <%= (ENV['test_urs_edsc_access_token'] || 'edsc-access').inspect %>
    refresh_token: <%= (ENV['test_urs_edsc_refresh_token'] || 'edsc-refresh').inspect %>
  expired_token:
    <<: *token_defaults
    access_token: <%= (ENV['test_urs_expired_access_token'] || 'expired-access').inspect %>
    refresh_token: <%= (ENV['test_urs_expired_refresh_token'] || 'expired-refresh').inspect %>
    expires_in: 1
  edscbasic:
    <<: *token_defaults
    access_token: <%= (ENV['test_urs_edscbasic_access_token'] || 'edscbasic-access').inspect %>
    refresh_token: <%= (ENV['test_urs_edscbasic_refresh_token'] || 'edscbasic-refresh').inspect %>
